name: agok_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.2"

dependencies:
  animated_text_kit: ^4.2.2
  auto_route: ^4.0.1
  auto_size_text: ^3.0.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  day_night_switcher: ^0.2.0+1
  dio: ^4.0.6
  dynamic_themes: ^1.1.0
  easy_localization: ^3.0.1
  feather_icons: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  getwidget: ^2.0.5
  google_fonts: ^2.3.2
  logger: ^1.1.0
  lottie: ^1.3.0
  retry: ^3.1.0
  rive: ^0.8.4
  simple_animations: ^4.2.0
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.1.4

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11

  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/language/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
